In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# /content/titanic_train.csv파일을 데이터프레임 객체로 불러오기
# head() 확인
# 데이터 수:, 특성수:, 각 특성의 데이터 타입, 결측치확인: , 중복확인:

In [2]:
#타이타닉 불러오기
#미싱데이터 없애기 1. 결측치가 500개 이사인 열 없에기, 2. 결측치가 하나라도 있는 행 모두 앖애기
#중복데이터 제거
titanic=pd.read_csv("/content/titanic_train.csv")
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [3]:
titanic.drop("Cabin", axis=1, inplace=True)
titanic.dropna(how="any", inplace=True)
titanic.drop_duplicates( inplace=True)

In [4]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Name         712 non-null    object
 4   Sex          712 non-null    object
 5   Age          712 non-null    float64
 6   SibSp        712 non-null    int64
 7   Parch        712 non-null    int64
 8   Ticket       712 non-null    object
 9   Fare         712 non-null    float64
 10  Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 66.8+ KB

In [5]:
titanic["Pclass"].value_counts()

3    355
1    184
2    173
Name: Pclass, dtype: int64

In [6]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [7]:
titanic=titanic[["Survived",	"Pclass",	"Sex",	"Age" ,"Fare"]]
titanic.groupby([ "Survived", "Pclass"]).size()

Survived  Pclass
0         1          64
          2          90
          3         270
1         1         120
          2          83
          3          85
dtype: int64

In [8]:
titanic.groupby([ "Survived", "Pclass"]).size().unstack()

Pclass      1   2    3
Survived
0          64  90  270
1         120  83   85

In [9]:
titanic.pivot_table("Age",index=["Survived"], columns=["Pclass"], aggfunc="count", margins=True)

Pclass      1    2    3  All
Survived
0          64   90  270  424
1         120   83   85  288
All       184  173  355  712

In [10]:
titanic["Survived"].groupby(titanic["Pclass"]).mean()

Pclass
1    0.652174
2    0.479769
3    0.239437
Name: Survived, dtype: float64

In [14]:
titanic["Age"].value_counts().sort_index()

0.42     1
0.67     1
0.75     2
0.83     2
0.92     1
        ..
70.00    2
70.50    1
71.00    2
74.00    1
80.00    1
Name: Age, Length: 88, dtype: int64

In [23]:
names = [10,20,30,40,50,60,70,80]
titanic["age_interval"] = pd.cut(titanic["Age"],8, labels = names)
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Survived      712 non-null    int64
 1   Pclass        712 non-null    int64
 2   Sex           712 non-null    object
 3   Age           712 non-null    float64
 4   Fare          712 non-null    float64
 5   age_interval  712 non-null    category
dtypes: category(1), float64(2), int64(2), object(1)
memory usage: 34.4+ KB

In [24]:
titanic["age_interval"].value_counts()

30    230
40    154
20    115
50     86
10     64
60     42
70     16
80      5
Name: age_interval, dtype: int64

In [25]:
titanic.pivot_table("Age",index=["Survived"], columns=["age_interval"], aggfunc="count")

age_interval  10  20   30  40  50  60  70  80
Survived
0             26  71  146  86  53  25  13   4
1             38  44   84  68  33  17   3   1

In [30]:
titanic["Survived"].groupby([titanic["Sex"], titanic["age_interval"]]).mean().unstack()

age_interval,10,20,30,40,50,60,70,80
Sex,,,,,,,,
female,0.612903,0.739130,0.753086,0.833333,0.677419,0.928571,1.000000,NaN
male,0.575758,0.144928,0.154362,0.230000,0.218182,0.142857,0.071429,0.2